import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Infobox from "@/components/infobox";
import Switcher from "@/components/switcher/Switcher";
import Navbar from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
          <Navbar />
      </header>
      <main className={`${styles.main} ${inter.className}`}>
        <>
          <Switcher planet="earth" selectedElement="01" />
          <Switcher planet="mars" selectedElement="01" />
        </>
      </main>
      <div className={styles.infoboxContainer}>
        <Infobox label="ROTATION TIME" title="58.6 DAYS" />
      </div>
    </>
  );
}
